# Generated by Django 5.1.2 on 2024-10-22 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banker',
            fields=[
                ('account_holder_name', models.CharField(max_length=100)),
                ('account_number', models.IntegerField(primary_key='account_number', serialize=False)),
                ('ifsc_code', models.CharField(max_length=11)),
                ('branch_name', models.CharField(max_length=100)),
                ('email_id', models.EmailField(max_length=254)),
                ('contact_number', models.IntegerField(max_length=10)),
                ('salary', models.IntegerField()),
            ],
        ),
    ]
